twig:
    file_name_pattern: '*.twig'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        app_images_profil_directory: '%public_uploads_directory%'

when@test:
    twig:
        strict_variables: true
